grails-app/controllers/ArchiveController.groovy
class ArchiveController {

    def index = { }

    def list = {
        def c = Entry.createCriteria()
        def entries = c {
            isNotNull('enclosureURL')
            lt("created", new Date())
            order("created", "desc")

        }
        [entries:entries]
    }
}

grails-app/views/layouts/_left.gsp
<!-- Start of Flickr -->
<div class="section">special stuff</div>
<div class="defaultContainer">
  <g:link controller="archive" action="list">Podcast Archive</g:link><br/>
  <g:link controller="entry">Admin</g:link><br/>
</div>

<div class="flickr topSpace" id="flickr">

</div>
<!-- End of Flickr -->

grails-app/views/layouts/_right.gsp
	      			<div class="section">search</div>
	      			<div class="defaultContainer">
					    <div id="autoCompleteSearch">
					        <input type="text" id="searchBox" value="search term"/>
					        <div id="searchContainer"></div>
					    </div>
	      			</div>

	      			<div class="section topSpace">updates</div>
	      			<!-- start twitter -->
					<div class="twitter">
					<ul id="twitter_update_list"></ul>
					</div>

                    <!-- twitter js -->
                    <script type="text/javascript" src="http://twitter.com/javascripts/blogger.js"></script>
                    <script type="text/javascript" src="http://twitter.com/statuses/user_timeline/grailspodcast.json?callback=twitterCallback2&count=3"></script>
                    <!-- twitter js -->

	      			<div class="section topSpace">social goodness</div>
					<div class="defaultContainer">
						<a href="http://www.flickr.com/search/?q=grailspodcast&m=tags">Flickr tag: 'grailspodcast'</a><br/>
						<a href="http://twitter.com/grailspodcast">Follow us on Twitter!</a><br/>
						<a href="mailto:grails.podcast@gmail.com">grails.podcast@gmail.com</a><br/>
						<a href="http://groups.google.com/group/grailspodcast">Grails Podcast Google Group</a>
					</div>

	      			<div class="section topSpace">our sponsors</div>
					<div class="defaultContainer center">
     
                                        <!--<a href="http://www.g2ix.com"><img src="http://www.g2ix.com/assets/g2ix/files/images/ad.gif"/></a -->
					</div>

	      			<div class="section topSpace">feeds</div>
					<div class="defaultContainer">
						<a href="http://feeds.grailspodcast.com/grailspodcast" title="Subscribe to our feed" rel="alternate" type="application/rss+xml"><img src="http://www.feedburner.com/fb/images/pub/feed-icon16x16.png" alt="" style="border:0"/></a> <a href="http://feeds.grailspodcast.com/grailspodcast" title="Subscribe to our feed" rel="alternate" type="application/rss+xml">Subscribe in a reader</a><br/>
						<a href="http://www.feedburner.com/fb/a/emailverifySubmit?feedId=1798222&amp;loc=en_US">Subscribe by Email</a><br/>
                                                <a href="http://feeds.grailspodcast.com/grailspodcast"><img src="http://feeds.feedburner.com/~fc/grailspodcast?bg=000000&fg=FFFFFF&anim=1&label=listeners" height="26" width="88" style="border:0" alt="" /></a>
					</div>

	      			<div class="section topSpace">about</div>
	      			<div class="defaultContainer">
	      			The Grails Podcast is a bi-weekly podcast about the <a href="http://groovy.codehaus.org">Groovy</a> scripting language, the <a href="http://www.grails.org">Grails</a>
	      			Web Framework and more. It is run by <a href="http://blogs.bytecode.com.au/glen">Glen Smith</a> from Canberra, Australia and <a href="http://hansamann.wordpress.com">Sven Haiges</a> from Sunnyvale, California.
	      			</div>

	         		<div class="section topSpace">del.icio.us</div>
	      			<!-- del.icio.us -->
	      			<div class="delicious">
						<script type="text/javascript" src="http://feeds.delicious.com/v2/js/tags/hansamann?title=%20&count=70&sort=alpha&flow=cloud&name&showadd&color=BBBBBB-000000&size=12-24"></script>
	      			</div>
	      			<!-- del.icio.us -->

grails-app/views/layouts/authentication.gsp
<html>
<head>
	<link rel="stylesheet" href="${createLinkTo(dir:'css',file:'main.css')}" />
</head>
<body>
	<g:layoutBody/>
	<g:layoutHead/>
</body>
</html>

grails-app/views/layouts/blog.gsp
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
  <head>
    <title><g:layoutTitle default="grailspodcast.com - The Groovy &amp; Grails Podcast" /></title>
    <link rel="shortcut icon" href="${createLinkTo(dir:'images/grailspodcast',file:'favicon.ico')}" type="image/x-icon" />
    <script src="http://yui.yahooapis.com/2.5.2/build/yuiloader/yuiloader-beta-min.js"></script>
    <g:javascript src="grailspodcast/grailspodcast.js" />
    <g:layoutHead />
    <link rel="stylesheet" href="${createLinkTo(dir:'css',file:'blog.css')}" />
    <link href="http://feeds.grailspodcast.com/grailspodcast" rel="alternate" type="application/rss+xml" title="Grails Podcast Feed" />
  </head>
  <body class="yui-skin-sam">

    <div class="headerWrap">
      <div class="header">
        <span class="left" id="weatherHeader"></span>
        <span id="now"></span>
      </div>
    </div>

    <!-- #doc2 = 950px width, centered -->
    <div id="doc2" class="yui-t5">
      <div id="hd">
        <!-- header -->
        <g:link controller="blog">
          <img style="margin-top:40px;margin-bottom:10px;" src="${createLinkTo(dir:'images/grailspodcast',file:'head_grailspodcast.png')}" alt="GrailsPodcast" />
        </g:link>
      </div>
      <div id="bd">
        <!-- body -->

        <div id="yui-main">
          <div class="yui-b">
            <div class="yui-gf">
              <div class="yui-u first">
                <g:render template="/layouts/left"/>
              </div>
              <div class="yui-u" id="content">
                <g:layoutBody />
              </div>
            </div>

          </div>
        </div>

        <div class="yui-b">

          <g:render template="/layouts/right" />

        </div>

      </div>
      <div id="ft">
        <!-- footer -->
        <div class="round">grailspodcast.com <g:meta name="app.version"/> on Grails <g:meta name="app.grails.version"/> | created by <a href="http://hansamann.wordpress.com">Sven Haiges</a> | This blog is published under the <a href="http://creativecommons.org/licenses/by-nc/3.0/us/">Creative Commons Attribution-Noncommercial 3.0 License</a>. </div>
      </div>
    </div>

    <script type="text/javascript">
      var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
      document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
    </script>
    <script type="text/javascript">
      try {
        var pageTracker = _gat._getTracker("UA-8635132-1");
        pageTracker._trackPageview();
      } catch(err) {}
    </script>

  </body>
</html>

grails-app/views/layouts/bloglayout.gsp
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd"> 
<html>
    <head>
        <title><g:layoutTitle default="grailspodcast.com - The Groovy &amp; Grails Podcast" /></title>
        <link rel="shortcut icon" href="${createLinkTo(dir:'images/grailspodcast',file:'favicon.ico')}" type="image/x-icon" />
        <g:layoutHead />
        <link rel="stylesheet" href="${createLinkTo(dir:'css',file:'blog.css')}" />		
        <link href="http://feeds.grailspodcast.com/grailspodcast" rel="alternate" type="application/rss+xml" title="Grails Podcast Feed" />
        <script type="text/javascript" src="http://static.delicious.com/js/playtagger.js"></script>	
        <meta name="verify-v1" content="m4T3qEhWQnrgrSJ3lqqHqKsMthninFsWFiKc0pRvxQ8=" />
    </head>
    <body class="yui-skin-sam">
        <g:layoutBody />
        <g:render template="/blog/test"/>
    <!-- create a blog layout and change the blog and calendar for it. add the now stirng into the json call for the weather info
    <!-- create a new controller which only does the weather and colors etc. -->
    </body>	
</html>

grails-app/views/layouts/iphone.gsp
<html>
    <head>
        <title><g:layoutTitle default="iPhone" /></title>
        <style type="text/css" media="screen">@import "${createLinkTo(dir:'js/iui',file:'iui.css')}";</style>
        <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;">
        <link rel="apple-touch-icon" href="${createLinkTo(dir:'images',file:'apple-touch-icon.png')}"/>
        <link rel="shortcut icon" href="${createLinkTo(dir:'images',file:'favicon.ico')}" type="image/x-icon" />
        <g:layoutHead />
        <g:javascript library="iui" />
        <g:javascript library="application" />				
    </head>
    <body>
        <g:layoutBody />		
    </body>	
</html>

grails-app/views/layouts/main.gsp
<html>
    <head>
        <title><g:layoutTitle default="grailspodcast.com - The Groovy &amp; Grails Podcast" /></title>
        <link rel="shortcut icon" href="${createLinkTo(dir:'images',file:'favicon.ico')}" type="image/x-icon" />
        <g:layoutHead />
        <link rel="stylesheet" href="${createLinkTo(dir:'css',file:'main.css')}" />
        
        			
    </head>
    <body class="yui-skin-sam">
        <div id="spinner" class="spinner" style="display:none;">
            <img src="${createLinkTo(dir:'images',file:'spinner.gif')}" alt="Spinner" />
        </div>	
        <div class="logo"><img src="${createLinkTo(dir:'images/grailspodcast',file:'grailspodcast_internal.png')}" alt="Grails Podcast" /></div>
        <g:layoutBody />		
    </body>	
</html>